// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  // Source code for API Project to run on localhost
  // https://github.com/workcontrolgit/TalentManagement-ApiResources-Net7
  // apiEndpoint: 'https://localhost:44378/api/v1',
  apiEndpoint: 'https://cat-netcore-api.azurewebsites.net/api/v1',
  apiMockEndpoint: 'https://cat-netcore-api.azurewebsites.net/api/v1',
// settings for connection to Duende IdentityServer
oidc: {
  // source code for Duende IdentityServer to run on localhost
  // https://github.com/workcontrolgit/CATTokenService.AdminUI.Duende
  // issuer: 'https://localhost:44310', // running on localhost
  issuer: 'https://cat-token-identity.azurewebsites.net', // demo IdentityServer in Azure
  clientId: 'TalentManagement', // client id setup in IdentityServer4
  responseType: 'code', //code flow PKCE
  redirectUri: window.location.origin,
  postLogoutRedirectUri: window.location.origin,
  silentRefreshRedirectUri: window.location.origin + '/silent-refresh.html',
  scope: 'openid profile email roles app.api.employeeprofile.read', // Ask offline_access to support refresh token refreshes
  useSilentRefresh: true, // Needed for Code Flow to suggest using iframe-based refreshes
  silentRefreshTimeout: 50000, // For faster testing
  timeoutFactor: 0.25, // For faster testing
  sessionChecksEnabled: false,
  showDebugInformation: false, // Also requires enabling "Verbose" level in devtools
  clearHashAfterLogin: false, // https://github.com/manfredsteyer/angular-oauth2-oidc/issues/457#issuecomment-431807040,
  nonceStateSeparator: 'semicolon', // Real semicolon gets mangled by IdentityServer's URI encoding
},
};
